# 项目 api 环境变量配置
project:
  basicUrl: http://192.168.1.93:8080
  baseUrl: http://192.168.1.93:8080
  YunServicesUrl: http://192.168.1.147:15000
  highgisUrl: http://192.168.1.90:8086
  businessUrl: http://192.168.1.114:8081
  hgisServer: http://192.168.1.90:8085/master

# 业务组件库 @ktw/api 环境变量配置
kbus:
  basicUrl: http://192.168.1.93:8080
  YunServicesUrl: http://192.168.1.147:15000

# websocket服务地址

socket: http://192.168.1.93:8020

# raven服务监控地址
#  key: raven服务生成的唯一key
#  sentryUrl: sentry服务部署的地址
#  project: sentry中创建的项目名称
#  例子： https://${key}@${sentryUrl}/${project}

raven: https://${key}@${sentryUrl}/${project}

projectConfig:
  dictionaryId: 77e403e7fee343498dd5881d5ba5dd1b

# 系统路由配置

# path: string;  // 路由匹配路径
# component?: Component;  // 路由匹配的单一组件，多组件展示请使用components属性，异步路由 () => import('view/login/Login')
# name?: string; // 命名路由
# components?: { [name: string]: Component }; // 命名视图组件  同时（同级）展示多个视图，而不是嵌套展示时使用。
# redirect?: string | Location | Function;   // 路由重定向跳转
# props?: boolean | string | Function;  是否将路由参数作为props传递给路由组件 详细用法： https://router.vuejs.org/zh-cn/essentials/passing-props.html
# alias?: string | Array<string>;   { path: '/a', component: A, alias: '/b' }  访问/b等同访问/a
# children?: Array<RouteConfig>; // 嵌套路由
# beforeEnter?: (to: Route, from: Route, next: Function) => void;  详情见同级目录下index.js中关于路由钩子的注释部分
# meta?: any;  路由元信息 用以绑定该路由相关信息 详细用法：https://router.vuejs.org/zh-cn/advanced/meta.html
# caseSensitive?: boolean; // 匹配规则是否大小写敏感？(默认值：false)
# pathToRegexpOptions?: Object; // 编译正则的选项

# 详情见： https://router.vuejs.org/zh-cn/api/options.html#routes

# 路由白名单 匹配该路径的地址将不会被校验权限
whiteList:
  - '/login'

# 异步权限路由
# 示例：
# routes:
#   SpaceQuery:  路由名称
#     path: '/spacequery'  路由路径
#     component: 'view/spacequery/SpaceQuery'  组件路径

routes:
  DashBoard:
    path: '/'
    component: 'view/dashboard/DashBoard'
    redirect: '/datamanager'
    children:
      DataManager:
        path: 'datamanager'
        component: 'view/datamanager/DataManager'
      MapView:
        path: 'mapview'
        component: 'view/mapview/MapView'
      MapEdit:
        path: 'mapedit'
        component: 'view/mapedit/MapEdit'
      Business:
        path: 'business'
        component: 'view/business/businessDataManager'
